apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: paulrishav93/kubia
        ports:
        - containerPort: 8080
