apiVersion: v1
kind: Service
metadata:
  name: kubia-service
spec:
  type: NodePort
  ports:
    - port: 80  # External port
      targetPort: 8080  # Port the container listens on
      nodePort: 30000  # External port to access service
  selector:
    app: kubia
