apiVersion: v1
kind: Service
metadata:
  name: kubia-service
spec:
  type: NodePort
  ports:
    - port: 80 # kubectl port-forward service/kubia-service 8080:80
      targetPort: 8080
      nodePort: 30000 
  selector:
    app: kubia
